apiVersion: batch/v1
kind: Job
metadata:
  name: restore
spec:
  template:
    spec:
      serviceAccountName: sa-mysql-restore
      containers:
          - name: restore-mysqldb
            image: saturnops01/mysqlrestore:latest
            env:
            - name: MYSQL_HOST
              value: mysqldb-primary-headless.{{ .Release.Namespace }}.svc.cluster.local
            - name: MYSQL_USER
              value: {{ .Values.auth.username }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: mysqldb
                    key: mysql-root-password
            - name: MYSQL_BUCKET_URI
              valueFrom:
                secretKeyRef:
                  name: mysql-bucket-uri-restore
                  key: MYSQL_BUCKET_URI
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-mysql-restore
                  key: AWS_DEFAULT_REGION
      restartPolicy: Never
  backoffLimit: 4
