apiVersion: v1
kind: Secret
metadata:
  name: mysql-bucket-uri-restore
  namespace:  {{ .Release.Namespace }}
  labels:
data:
  MYSQL_BUCKET_URI: {{ .Values.restore.bucket_uri | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-mysql-restore
  namespace:  {{ .Release.Namespace }}
  labels:
data:
  AWS_DEFAULT_REGION: {{ .Values.restore.aws_default_region | b64enc }}
---
