apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-mysql-backup
  namespace: mysqldb
  annotations: {{.Values.annotations}}
    # iam.gke.io/gcp-service-account: test-mysql-backup@fresh-sanctuary-389006.iam.gserviceaccount.com
  #   eks.amazonaws.com/role-arn: {{ .Values.s3.role_arn }}
