## Enable Full backup
backup:
  bucket_uri: ${bucket_uri}
  aws_default_region: ${s3_bucket_region}
  cron_for_full_backup: "${cron_for_full_backup}"


annotations:
  ${annotations}

auth:
  username: "${custom_user_username}"

provider_type: ${provider_type}